insert into "USER" ("ID","ROLE","FIRST_NAME","LAST_NAME","URL_IMAGE","USERNAME","PASSWORD") values(NEXTVAL('"USER_SEQ"'),'ADMIN','Mario','Iaccarino','https://th.bing.com/th/id/OIP.oM5FP1fsXXR6ScsBZs2dPgHaKj?w=178&h=224&c=7&r=0&o=5&pid=1.7','marioiaccarino@gmail.com','$2a$12$Y.L4hRzMA54mMJhrhpaKme/hIIGvdiXIb7b0sVmr0Rn.AbSv0ywGC');
insert into "COMMUNITY" ("ID", "NAME","IS_PUBLIC","LOGO") values (NEXTVAL('"COMMUNITY_SEQ"'), 'Chess Club', true,'https://th.bing.com/th/id/OIP.d81ud5DwhQf1Kdzgu-8HlgHaE9?w=233&h=180&c=7&r=0&o=5&pid=1.7'  );
insert into "USER_COMMUNITY" ("ID", "REFERRED_USER", "COMMUNITY", "NICKNAME") values (NEXTVAL('"USER_COMMUNITY_SEQ"'),1,1,'MarioJR');
insert into "COMMUNITY" ("ID", "NAME","IS_PUBLIC","LOGO") values (NEXTVAL('"COMMUNITY_SEQ"'), 'Politics', true,'https://th.bing.com/th/id/OIP.0NYa-ghWKOnkNrjQuVAv4wHaEc?pid=ImgDet&w=191&h=114&c=7');
insert into "USER_COMMUNITY" ("ID", "REFERRED_USER", "COMMUNITY", "NICKNAME") values (NEXTVAL('"USER_COMMUNITY_SEQ"'),1,51,'Mario Draghi');
insert into "POST" ("ID","TITLE","DESCRIPTION","URL_IMAGE","AUTHOR") values (NEXTVAL('"POST_SEQ"'), 'Magnus the greatest', 'Magnus Carlsen recently won the Superbet Rapid & Blitz Poland 2024, showcasing his exceptional skills and solidifying his reputation as one of the greatest chess players of all time.','https://th.bing.com/th/id/OIP.n5FP2NK62-3FvnJRVfY4twHaGE?w=225&h=185&c=7&r=0&o=5&pid=1.7',1);
insert into "POST" ("ID","TITLE","DESCRIPTION","URL_IMAGE","AUTHOR") values (NEXTVAL('"POST_SEQ"'), 'European votes, Italy 2024', 'The right is advancing throughout Europe. In Italy the Brothers of Italy wins hands down, the Democratic Party does well. In France Macron sends the country to elections, in Germany the ultra-right overtakes Chancellor Scholz''s party','https://th.bing.com/th/id/OIF.NNPn6VohL8tmrQE9SeM0Gg?w=259&h=180&c=7&r=0&o=5&pid=1.7',51);
insert into "COMMUNITY" ("ID","NAME","IS_PUBLIC","LOGO") values (NEXTVAL('"COMMUNITY_SEQ"'), 'Supercell Italia', true,'https://th.bing.com/th/id/OIP.Fon1cE9gfc9RzkJAMXlrCwHaDq?w=295&h=172&c=7&r=0&o=5&pid=1.7');

